spring:
  data:
    redis:
      host: 192.168.0.15
      password: 'dlwmal42'
      port: 6379

logging:
  level:
    root: info
    org:
      springframework: info
    web: info

server:
  error:
    include-stacktrace: always

